spring:
  application:
    name: my-cloud-monitor-scheduler
  data:
    mongodb:
      authentication-database: admin
      database: myidsrvdb
      username: myidsrvdbuser
      password: myidsrvdbpwd@1234
      port: 27017
      host: localhost

logging:
  level:
    org:
      springframework: INFO
    com:
      developerhelperhub: DEBUG
      netflix:
        eureka: OFF
        discovery: OFF

server:
  port: 8088
  #servlet:
  #  context-path: /monitor  

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:discoverypass@localhost:8761/eureka/

      
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics, hystrix.stream