spring:
  application:
    name: my-cloud-monitor-scheduler
  jmx:
    enabled: true
  data:
    mongodb:
      authentication-database: ${ENV_MYC_MONITOR_SCHD_MONGO_AUTH_DB}
      database: ${ENV_MYC_MONITOR_SCHD_MONGO_DB}
      username: ${ENV_MYC_MONITOR_SCHD_MONGO_USERNAME}
      password: ${ENV_MYC_MONITOR_SCHD_MONGO_PASSWORD}
      port: ${ENV_MYC_MONITOR_SCHD_MONGO_PORT}
      host: ${ENV_MYC_MONITOR_SCHD_MONGO_HOST}

mycloud:
  oauth:
    id: identity-service
    client-id: ${ENV_MYC_IDENTIY_CLIENT_ID}
    client-secret: ${ENV_MYC_IDENTIY_CLIENT_SECRET}
    grant-type: client_credentials
    scop: ADMIN
    access-token-uri: http://${ENV_MYC_IDENTIY_HOST}:${ENV_MYC_IDENTIY_PORT}/oauth/token
  influxdb:
    database: ${ENV_MYC_MONITOR_SCHD_INFLUX_DB}
    username: ${ENV_MYC_MONITOR_SCHD_INFLUX_USERNAME}
    password: ${ENV_MYC_MONITOR_SCHD_INFLUX_PASSWORD}
    port: ${ENV_MYC_MONITOR_SCHD_INFLUX_PORT}
    host: ${ENV_MYC_MONITOR_SCHD_INFLUX_HOST}

server:
  port: 8088
  tomcat:
    accesslog:
      enabled: true
      directory: /var/mycloud/logs/access_logs
      prefix: access_log
      buffered: false
      suffix: .log
      pattern: "%t|%a|%h|%p|%m|%U|%q|%s|%D|%T|%F|%l|%S|%I|%v|%u"
  #servlet:
  #  context-path: /monitor  

eureka:
  client:
    serviceUrl:
      defaultZone: http://${ENV_MYC_DISCOVERY_USERNAME}:${ENV_MYC_DISCOVERY_PASSWORD}@${ENV_MYC_DISCOVERY_HOST}:${ENV_MYC_DISCOVERY_PORT}/eureka/
  instance:
    preferIpAddress: true
      
management:
  server:
    port: 9005
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - jolokia
    jmx:
      exposure:
        include:
          - info
          - health
          - metrics