spring:
  application:
    name: my-cloud-circuit-breaker
  security:
    user:
      name: breaker
      password: breaker

logging:
  level:
    org:
      springframework: DEBUG
    com:
      developerhelperhub: DEBUG
      netflix:
        eureka: OFF
        discovery: OFF

server:
  port: 8086
  

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:discoverypass@localhost:8761/eureka/
