spring:
  application:
    name: my-cloud-config
  jmx:
    enabled: true
  data:
    mongodb:
      authentication-database: ${ENV_MYC_CONFIG_MONGO_AUTH_DB}
      database: ${ENV_MYC_CONFIG_MONGO_DB}
      username: ${ENV_MYC_CONFIG_MONGO_USERNAME}
      password: ${ENV_MYC_CONFIG_MONGO_PASSWORD}
      port: ${ENV_MYC_CONFIG_MONGO_PORT}
      host: ${ENV_MYC_CONFIG_MONGO_HOST}
  cloud:
    config:
      server:
        git:
          uri: file://${ENV_MYC_CONFIG_SERVER_URI_PATH}/config-repo

      
server:
  port: 8089
  tomcat:
    accesslog:
      enabled: true
      directory: /var/mycloud/logs/access_logs
      prefix: access_log
      buffered: false
      suffix: .log
      pattern: "%t|%a|%h|%p|%m|%U|%q|%s|%D|%T|%F|%l|%S|%I|%v|%u"
  #servlet:
  #  context-path: /monitor  

eureka:
  client:
    serviceUrl:
      defaultZone: http://${ENV_MYC_DISCOVERY_USERNAME}:${ENV_MYC_DISCOVERY_PASSWORD}@${ENV_MYC_DISCOVERY_HOST}:${ENV_MYC_DISCOVERY_PORT}/eureka/
  instance:
    preferIpAddress: true


      
management:
  server:
    port: 9006
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - jolokia
    jmx:
      exposure:
        include:
          - info
          - health
          - metrics