spring:
  application:
    name: my-cloud-identity
  data:
    mongodb:
      authentication-database: admin
      database: myidsrvdb
      port: 27017
      host: localhost
      
logging:
  level:
    org:
      springframework: DEBUG
    com:
      developerhelperhub: DEBUG

server:
  port: 8081
  servlet:
    context-path: /identity

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:discoverypass@localhost:8761/eureka/

      
#logging.level.org.springframework=DEBUG
#logging.level.com.developerhelperhub=DEBUG
#
#server.port=8081
#server.servlet.context-path=/auth
#
#spring.data.mongodb.authentication-database=admin
#spring.data.mongodb.database=myidsrvdb
#spring.data.mongodb.port=27017
#spring.data.mongodb.host=localhost
      