spring:
  application:
    name: my-cloud-identity
  jmx:
    enabled: true
  data:
    mongodb:
      authentication-database: ${ENV_MYC_IDENTIY_MONGO_AUTH_DB}
      database: ${ENV_MYC_IDENTIY_MONGO_DB}
      username: ${ENV_MYC_IDENTIY_MONGO_USERNAME}
      password: ${ENV_MYC_IDENTIY_MONGO_PASSWORD}
      port: ${ENV_MYC_IDENTIY_MONGO_PORT}
      host: ${ENV_MYC_IDENTIY_MONGO_HOST}
      
logging:
  level:
    org:
      springframework: DEBUG
    com:
      developerhelperhub: DEBUG

server:
  port: 8081
#  servlet:
#    context-path: /identity

eureka:
  client:
    serviceUrl:
      defaultZone: http://${ENV_MYC_DISCOVERY_USERNAME}:${ENV_MYC_DISCOVERY_PASSWORD}@${ENV_MYC_DISCOVERY_HOST}:${ENV_MYC_DISCOVERY_PORT}/eureka/


management:
  server:
    port: 9002
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - jolokia
    jmx:
      exposure:
        include:
          - info
          - health
          - metrics