spring:
  application:
    name: my-cloud-identity
  data:
    mongodb:
      authentication-database: admin
      database: myidsrvdb
      port: 27017
      host: localhost
      
logging:
  level:
    org:
      springframework: DEBUG
    com:
      developerhelperhub: DEBUG

server:
  port: 8081
#  servlet:
#    context-path: /identity

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:discoverypass@localhost:8761/eureka/


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics