apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-influxdb
  namespace: my-cloud-local
  labels:
    app.mycloud.io/name: influxdb
    app.mycloud.io/version: 1.0.0
    app.mycloud.io/component: volume-claim
    app.mycloud.io/part-of: volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: my-cloud-local
  labels:
    app.mycloud.io/name: influxdb
    app.mycloud.io/version: 1.0.0
    app.mycloud.io/component: database
    app.mycloud.io/part-of: backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app.mycloud.io/name: influxdb

  template:
    metadata:
      labels:
        app.mycloud.io/name: influxdb

    spec:
      containers:
        - name: influxdb
          image: influxdb
          volumeMounts: 
            - name: vol-influxdb
              mountPath: /var/lib/influxdb
              
          env:
            - name: INFLUX_USERNAME
              value: todd
            - name: INFLUX_PASSWORD
              value: influxdb4ever
          ports:
            - containerPort: 8086

      volumes:
        - name: vol-influxdb
          persistentVolumeClaim:
            claimName: pvc-influxdb

---
kind: Service
apiVersion: v1
metadata:
  name: influxdb
  namespace: my-cloud-local
  labels:
    app.mycloud.io/name: influxdb
    app.mycloud.io/version: 1.0.0
    app.mycloud.io/component: database
    app.mycloud.io/part-of: backend

spec:
  selector:
    app.mycloud.io/name: influxdb
    
  ports:
    - name: transport
      protocol: TCP
      port: 8086
      targetPort: 8086