apiVersion: v1
kind: Namespace
metadata:
  name: my-cloud-local

---  
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  namespace: my-cloud-local
  labels:
    app.mycloud.io/name: presistent
    app.mycloud.io/version: 1.0.0
    app.mycloud.io/component: volume
    app.mycloud.io/part-of: volume
    app.mycloud.io/type: local
spec:
  # storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/mycloud/volume"