apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
  namespace: my-cloud-local
  labels:
    app.mycloud.io/name: monitor
    app.mycloud.io/version: 1.0.0
    app.mycloud.io/component: micorserivce
    app.mycloud.io/part-of: backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app.mycloud.io/name: monitor

  template:
    metadata:
      labels:
        app.mycloud.io/name: monitor

    spec:
      containers:
        - name: monitor
          image: developerhelperhub/my-cloud-monitor
              
          env:
            - name: ENV_MYC_DISCOVERY_USERNAME
              value: discovery
            - name: ENV_MYC_DISCOVERY_PASSWORD
              value: discoverypass
            - name: ENV_MYC_DISCOVERY_HOST
              value: discovery
            - name: ENV_MYC_DISCOVERY_PORT
              value: "8761"
            - name: ENV_MYC_MONITOR_MONGO_DB
              value: myidsrvdb
            - name: ENV_MYC_MONITOR_MONGO_AUTH_DB
              value: admin
            - name: ENV_MYC_MONITOR_MONGO_USERNAME
              value: myidsrvdbuser
            - name: ENV_MYC_MONITOR_MONGO_PASSWORD
              value: myidsrvdbpwd@1234
            - name: ENV_MYC_MONITOR_MONGO_PORT
              value: "27017"
            - name: ENV_MYC_MONITOR_MONGO_HOST
              value: mongodb
            - name: ENV_MYC_MONITOR_INFLUX_DB
              value: mycloudmonitordb
            - name: ENV_MYC_MONITOR_INFLUX_USERNAME
              value: todd
            - name: ENV_MYC_MONITOR_INFLUX_PASSWORD
              value: influxdb4ever
            - name: ENV_MYC_MONITOR_INFLUX_HOST
              value: influxdb
            - name: ENV_MYC_MONITOR_INFLUX_PORT
              value: "8086"
            - name: ENV_MYC_FILEBEAT_ELASTICSEARCH_HOSTS
              value: '["elasticsearch:9200"]'
            - name: ENV_MYC_FILEBEAT_LOGGING_LEVEL
              value: info
            - name: ENV_MYC_ELASTICSEARCH_HOST
              value: elasticsearch
            - name: ENV_MYC_ELASTICSEARCH_PORT
              value: "9300"
            - name: ENV_MYC_ELASTICSEARCH_CLUSTER_NAME
              value: docker-cluster
            - name: JAVA_OPTS
              value: >
                -Dspring.profiles.active=staging
                -Djava.rmi.server.logCalls=true
                -Djava.rmi.server.hostname=localhost
                -Dcom.sun.management.jmxremote=true
                -Dcom.sun.management.jmxremote.local.only=false 
                -Dcom.sun.management.jmxremote.port=7004
                -Dcom.sun.management.jmxremote.rmi.port=7004
                -Dcom.sun.management.jmxremote.ssl=false 
                -Dcom.sun.management.jmxremote.authenticate=false
          ports:
            - containerPort: 8087
            - containerPort: 9004

---
kind: Service
apiVersion: v1
metadata:
  name: monitor
  namespace: my-cloud-local
  labels:
    app.mycloud.io/name: monitor
    app.mycloud.io/version: 1.0.0
    app.mycloud.io/component: micorserivce
    app.mycloud.io/part-of: backend

spec:
  selector:
    app.mycloud.io/name: monitor
    
  ports:
    - name: jmx-management
      protocol: TCP
      port: 9004
      targetPort: 9004
    - name: http
      protocol: TCP
      port: 8087
      targetPort: 8087