apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: my-cloud-local
  labels:
    app.mycloud.io/name: api-gateway
    app.mycloud.io/version: 1.0.0
    app.mycloud.io/component: micorserivce
    app.mycloud.io/part-of: backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app.mycloud.io/name: api-gateway

  template:
    metadata:
      labels:
        app.mycloud.io/name: api-gateway

    spec:
      containers:
        - name: api-gateway
          image: developerhelperhub/my-cloud-api-gateway
              
          env:
            - name: ENV_MYC_DISCOVERY_USERNAME
              value: discovery
            - name: ENV_MYC_DISCOVERY_PASSWORD
              value: discoverypass
            - name: ENV_MYC_DISCOVERY_HOST
              value: discovery
            - name: ENV_MYC_DISCOVERY_PORT
              value: "8761"
            - name: ENV_MYC_FILEBEAT_ELASTICSEARCH_HOSTS
              value: '["elasticsearch:9200"]'
            - name: ENV_MYC_FILEBEAT_LOGGING_LEVEL
              value: info
            - name: JAVA_OPTS
              value: >
                -Dspring.profiles.active=staging
                -Djava.rmi.server.logCalls=true
                -Djava.rmi.server.hostname=localhost
                -Dcom.sun.management.jmxremote=true
                -Dcom.sun.management.jmxremote.local.only=false 
                -Dcom.sun.management.jmxremote.port=7003
                -Dcom.sun.management.jmxremote.rmi.port=7003
                -Dcom.sun.management.jmxremote.ssl=false 
                -Dcom.sun.management.jmxremote.authenticate=false
          ports:
            - containerPort: 8085
            - containerPort: 9003

---
kind: Service
apiVersion: v1
metadata:
  name: api-gateway
  namespace: my-cloud-local
  labels:
    app.mycloud.io/name: api-gateway
    app.mycloud.io/version: 1.0.0
    app.mycloud.io/component: micorserivce
    app.mycloud.io/part-of: backend

spec:
  selector:
    app.mycloud.io/name: api-gateway
    
  ports:
    - name: jmx-management
      protocol: TCP
      port: 9003
      targetPort: 9003
    - name: http
      protocol: TCP
      port: 8085
      targetPort: 8085