apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery
  namespace: my-cloud-local
  labels:
    app.mycloud.io/name: discovery
    app.mycloud.io/version: 1.0.0
    app.mycloud.io/component: micorserivce
    app.mycloud.io/part-of: backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app.mycloud.io/name: discovery

  template:
    metadata:
      labels:
        app.mycloud.io/name: discovery

    spec:
      containers:
        - name: discovery
          image: developerhelperhub/my-cloud-discovery
              
          env:
            - name: ENV_MYC_DISCOVERY_USERNAME
              value: discovery
            - name: ENV_MYC_DISCOVERY_PASSWORD
              value: discoverypass
            - name: ENV_MYC_DISCOVERY_HOST
              value: localhost
            - name: ENV_MYC_DISCOVERY_PORT
              value: "8761"
            - name: ENV_MYC_FILEBEAT_ELASTICSEARCH_HOSTS
              value: '["elasticsearch:9200"]'
            - name: ENV_MYC_FILEBEAT_LOGGING_LEVEL
              value: info
            - name: JAVA_OPTS
              value: >
                -Dspring.profiles.active=staging
                -Djava.rmi.server.logCalls=true
                -Djava.rmi.server.hostname=localhost
                -Dcom.sun.management.jmxremote=true
                -Dcom.sun.management.jmxremote.local.only=false 
                -Dcom.sun.management.jmxremote.port=7001
                -Dcom.sun.management.jmxremote.rmi.port=7001
                -Dcom.sun.management.jmxremote.ssl=false 
                -Dcom.sun.management.jmxremote.authenticate=false
          ports:
            - containerPort: 8761
            - containerPort: 9001

---
kind: Service
apiVersion: v1
metadata:
  name: discovery
  namespace: my-cloud-local
  labels:
    app.mycloud.io/name: discovery
    app.mycloud.io/version: 1.0.0
    app.mycloud.io/component: micorserivce
    app.mycloud.io/part-of: backend

spec:
  selector:
    app.mycloud.io/name: discovery
    
  ports:
    - name: jmx-management
      protocol: TCP
      port: 9001
      targetPort: 9001
    - name: http
      protocol: TCP
      port: 8761
      targetPort: 8761