spring:
  application:
    name: my-cloud-config-server
  jmx:
    enabled: true
  cloud:
    config:
      server:
        git:
          uri: ${ENV_MYC_CONFIG_SERVER_GIT_URI}
          # username: ${ENV_MYC_CONFIG_SERVER_GIT_USERNAME}
          # password: ${ENV_MYC_CONFIG_SERVER_GIT_PASSWORD}
  security:
    user:
      name: ${ENV_MYC_CONFIG_SERVER_USERNAME}
      password: ${ENV_MYC_CONFIG_SERVER_PASSWORD}

  
server:
  port: 8089

  tomcat:
    accesslog:
      enabled: true
      directory: /var/mycloud/logs/access_logs
      prefix: access_log
      buffered: false
      suffix: .log
      pattern: "%t|%a|%h|%p|%m|%U|%q|%s|%D|%T|%F|%l|%S|%I|%v|%u"
  #servlet:
  #  context-path: /monitor  

eureka:
  client:
    serviceUrl:
      defaultZone: http://${ENV_MYC_DISCOVERY_USERNAME}:${ENV_MYC_DISCOVERY_PASSWORD}@${ENV_MYC_DISCOVERY_HOST}:${ENV_MYC_DISCOVERY_PORT}/eureka/
  instance:
    preferIpAddress: true

management:
  server:
    port: 9006
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - jolokia
    jmx:
      exposure:
        include:
          - info
          - health
          - metrics