spring:
  application:
    name: my-cloud-monitor
  security:
    user:
      name: breaker
      password: breaker

logging:
  level:
    org:
      springframework: DEBUG
    com:
      developerhelperhub: DEBUG
      netflix:
        eureka: OFF
        discovery: OFF

server:
  port: 8087
  #servlet:
  #  context-path: /monitor  

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:discoverypass@localhost:8761/eureka/

      
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics