spring:
  application:
    name: my-cloud-api-gateway

logging:
  level:
    org:
      springframework: DEBUG

server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:discoverypass@localhost:8761/eureka/
    
zuul:
  routes:
    identity:
      path: /identity/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: my-cloud-identity
      stripPrefix: false
    discovery:
      path: /discovery/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: my-cloud-discovery
