version: '3'
services: 
  my-cloud-git-server:
    image: developerhelperhub/my-cloud-git-server
    container_name: my-cloud-git-server
    volumes:
      - /var/mycloud/volume/git/repos:/var/www/git
    ports:
      - '8087:80'
  my-cloud-mongodb:
    image: mongo
    container_name: my-cloud-mongodb
    environment:
      - MONGO_INITDB_DATABASE=myidsrvdb
      - MONGO_INITDB_ROOT_USERNAME=myidsrvdbuser
      - MONGO_INITDB_ROOT_PASSWORD=myidsrvdbpwd@1234
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - /var/mycloud/volume/db/mongo:/data/db
    ports:
      - '27017:27017'
  my-cloud-influxdb:
    image: influxdb
    container_name: my-cloud-influxdb
    environment:
      - INFLUX_USERNAME=todd
      - INFLUX_PASSWORD=influxdb4ever
    volumes:
      - /var/mycloud/volume/db/influx:/var/lib/influxdb
    ports:
      - '8086:8086'
  elasticsearch:
    image: elasticsearch:7.7.1
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    tty: true
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  # kibana:
  #   image: kibana:7.7.1
  #   container_name: kibana
  #   ports:
  #     - "5601:5601"
  my-cloud-discovery:
    image: developerhelperhub/my-cloud-discovery
    container_name: my-cloud-discovery
    environment:
      - ENV_MYC_DISCOVERY_USERNAME=discovery
      - ENV_MYC_DISCOVERY_PASSWORD=discoverypass
      - ENV_MYC_DISCOVERY_HOST=my-cloud-discovery
      - ENV_MYC_DISCOVERY_PORT=8761
      - ENV_MYC_FILEBEAT_ELASTICSEARCH_HOSTS=["elasticsearch:9200"]
      - ENV_MYC_FILEBEAT_LOGGING_LEVEL="info"
      - |
        JAVA_OPTS=
        -Dspring.profiles.active=staging
        -Djava.rmi.server.logCalls=true
        -Djava.rmi.server.hostname=localhost
        -Dcom.sun.management.jmxremote=true
        -Dcom.sun.management.jmxremote.local.only=false 
        -Dcom.sun.management.jmxremote.port=7001
        -Dcom.sun.management.jmxremote.rmi.port=7001
        -Dcom.sun.management.jmxremote.ssl=false 
        -Dcom.sun.management.jmxremote.authenticate=false
    ports:
      - '8761:8761'
      - '9001:9001'
  # my-cloud-identity:
  #   image: developerhelperhub/my-cloud-identity
  #   container_name: my-cloud-identity
  #   links:
  #     - my-cloud-mongodb
  #     - my-cloud-discovery
  #   environment:
  #     - ENV_MYC_DISCOVERY_USERNAME=discovery
  #     - ENV_MYC_DISCOVERY_PASSWORD=discoverypass
  #     - ENV_MYC_DISCOVERY_HOST=my-cloud-discovery
  #     - ENV_MYC_DISCOVERY_PORT=8761
  #     - ENV_MYC_IDENTIY_MONGO_DB=myidsrvdb
  #     - ENV_MYC_IDENTIY_MONGO_AUTH_DB=admin
  #     - ENV_MYC_IDENTIY_MONGO_USERNAME=myidsrvdbuser
  #     - ENV_MYC_IDENTIY_MONGO_PASSWORD=myidsrvdbpwd@1234
  #     - ENV_MYC_IDENTIY_MONGO_PORT=27017
  #     - ENV_MYC_IDENTIY_MONGO_HOST=my-cloud-mongodb
  #     - ENV_MYC_FILEBEAT_ELASTICSEARCH_HOSTS=["elasticsearch:9200"]
  #     - ENV_MYC_FILEBEAT_LOGGING_LEVEL="info"
  #     - |
  #       JAVA_OPTS=
  #       -Dspring.profiles.active=staging
  #       -Djava.rmi.server.logCalls=true
  #       -Djava.rmi.server.hostname=localhost
  #       -Dcom.sun.management.jmxremote=true
  #       -Dcom.sun.management.jmxremote.local.only=false
  #       -Dcom.sun.management.jmxremote.port=7002
  #       -Dcom.sun.management.jmxremote.rmi.port=7002
  #       -Dcom.sun.management.jmxremote.ssl=false 
  #       -Dcom.sun.management.jmxremote.authenticate=false
  #   ports:
  #     - '8081:8081'
  #     - '9002:9002'
  # my-cloud-api-gateway:
  #   image: developerhelperhub/my-cloud-api-gateway
  #   container_name: my-cloud-api-gateway
  #   links:
  #     - my-cloud-discovery
  #   environment:
  #     - ENV_MYC_DISCOVERY_USERNAME=discovery
  #     - ENV_MYC_DISCOVERY_PASSWORD=discoverypass
  #     - ENV_MYC_DISCOVERY_HOST=my-cloud-discovery
  #     - ENV_MYC_DISCOVERY_PORT=8761
  #     - ENV_MYC_FILEBEAT_ELASTICSEARCH_HOSTS=["elasticsearch:9200"]
  #     - ENV_MYC_FILEBEAT_LOGGING_LEVEL="info"
  #     - |
  #       JAVA_OPTS=
  #       -Dspring.profiles.active=staging
  #       -Djava.rmi.server.logCalls=true
  #       -Djava.rmi.server.hostname=localhost
  #       -Dcom.sun.management.jmxremote=true
  #       -Dcom.sun.management.jmxremote.local.only=false
  #       -Dcom.sun.management.jmxremote.port=7003
  #       -Dcom.sun.management.jmxremote.rmi.port=7003
  #       -Dcom.sun.management.jmxremote.ssl=false 
  #       -Dcom.sun.management.jmxremote.authenticate=false
  #   ports:
  #     - '8085:8085'
  #     - '9003:9003'
  # my-cloud-monitor:
  #   image: developerhelperhub/my-cloud-monitor
  #   container_name: my-cloud-monitor
  #   links:
  #     - my-cloud-mongodb
  #     - my-cloud-influxdb
  #     - my-cloud-discovery
  #     - my-cloud-identity
  #     - elasticsearch
  #   environment:
  #     - ENV_MYC_DISCOVERY_USERNAME=discovery
  #     - ENV_MYC_DISCOVERY_PASSWORD=discoverypass
  #     - ENV_MYC_DISCOVERY_HOST=my-cloud-discovery
  #     - ENV_MYC_DISCOVERY_PORT=8761
  #     - ENV_MYC_MONITOR_MONGO_DB=myidsrvdb
  #     - ENV_MYC_MONITOR_MONGO_AUTH_DB=admin
  #     - ENV_MYC_MONITOR_MONGO_USERNAME=myidsrvdbuser
  #     - ENV_MYC_MONITOR_MONGO_PASSWORD=myidsrvdbpwd@1234
  #     - ENV_MYC_MONITOR_MONGO_PORT=27017
  #     - ENV_MYC_MONITOR_MONGO_HOST=my-cloud-mongodb
  #     - ENV_MYC_MONITOR_INFLUX_DB=mycloudmonitordb
  #     - ENV_MYC_MONITOR_INFLUX_USERNAME=todd
  #     - ENV_MYC_MONITOR_INFLUX_PASSWORD=influxdb4ever
  #     - ENV_MYC_MONITOR_INFLUX_PORT=8086
  #     - ENV_MYC_MONITOR_INFLUX_HOST=my-cloud-influxdb
  #     - ENV_MYC_FILEBEAT_ELASTICSEARCH_HOSTS=["elasticsearch:9200"]
  #     - ENV_MYC_FILEBEAT_LOGGING_LEVEL="info"
  #     - ENV_MYC_ELASTICSEARCH_HOST=elasticsearch
  #     - ENV_MYC_ELASTICSEARCH_PORT=9300
  #     - ENV_MYC_ELASTICSEARCH_CLUSTER_NAME=docker-cluster
  #     - |
  #       JAVA_OPTS=
  #       -Dspring.profiles.active=staging
  #       -Djava.rmi.server.logCalls=true
  #       -Djava.rmi.server.hostname=localhost
  #       -Dcom.sun.management.jmxremote=true
  #       -Dcom.sun.management.jmxremote.local.only=false
  #       -Dcom.sun.management.jmxremote.port=7004
  #       -Dcom.sun.management.jmxremote.rmi.port=7004
  #       -Dcom.sun.management.jmxremote.ssl=false 
  #       -Dcom.sun.management.jmxremote.authenticate=false
  #   ports:
  #     - '8087:8087'
  #     - '9004:9004'
  # my-cloud-monitor-scheduler:
  #   image: developerhelperhub/my-cloud-monitor-scheduler
  #   container_name: my-cloud-monitor-scheduler
  #   links:
  #     - my-cloud-mongodb
  #     - my-cloud-influxdb
  #     - my-cloud-discovery
  #     - my-cloud-identity
  #   environment:
  #     - ENV_MYC_DISCOVERY_USERNAME=discovery
  #     - ENV_MYC_DISCOVERY_PASSWORD=discoverypass
  #     - ENV_MYC_DISCOVERY_HOST=my-cloud-discovery
  #     - ENV_MYC_DISCOVERY_PORT=8761
  #     - ENV_MYC_MONITOR_SCHD_MONGO_DB=myidsrvdb
  #     - ENV_MYC_MONITOR_SCHD_MONGO_AUTH_DB=admin
  #     - ENV_MYC_MONITOR_SCHD_MONGO_USERNAME=myidsrvdbuser
  #     - ENV_MYC_MONITOR_SCHD_MONGO_PASSWORD=myidsrvdbpwd@1234
  #     - ENV_MYC_MONITOR_SCHD_MONGO_PORT=27017
  #     - ENV_MYC_MONITOR_SCHD_MONGO_HOST=my-cloud-mongodb
  #     - ENV_MYC_MONITOR_SCHD_INFLUX_DB=mycloudmonitordb
  #     - ENV_MYC_MONITOR_SCHD_INFLUX_USERNAME=todd
  #     - ENV_MYC_MONITOR_SCHD_INFLUX_PASSWORD=influxdb4ever
  #     - ENV_MYC_MONITOR_SCHD_INFLUX_PORT=8086
  #     - ENV_MYC_MONITOR_SCHD_INFLUX_HOST=my-cloud-influxdb
  #     - ENV_MYC_IDENTIY_CLIENT_ID=my-cloud-identity-credentials
  #     - ENV_MYC_IDENTIY_CLIENT_SECRET=VkZpzzKa3uMq4vqg
  #     - ENV_MYC_IDENTIY_HOST=my-cloud-identity
  #     - ENV_MYC_IDENTIY_PORT=8081
  #     - ENV_MYC_FILEBEAT_ELASTICSEARCH_HOSTS=["elasticsearch:9200"]
  #     - ENV_MYC_FILEBEAT_LOGGING_LEVEL="info"
  #     - |
  #       JAVA_OPTS=
  #       -Dspring.profiles.active=staging
  #       -Djava.rmi.server.logCalls=true
  #       -Djava.rmi.server.hostname=localhost
  #       -Dcom.sun.management.jmxremote=true
  #       -Dcom.sun.management.jmxremote.local.only=false
  #       -Dcom.sun.management.jmxremote.port=7005
  #       -Dcom.sun.management.jmxremote.rmi.port=7005
  #       -Dcom.sun.management.jmxremote.ssl=false 
  #       -Dcom.sun.management.jmxremote.authenticate=false
  #   ports:
  #     - '8088:8088'
  #     - '9005:9005'

volumes:
    elasticsearch_data:
