version: '2.4'
services: 
  my-cloud-git-server:
    image: developerhelperhub/my-cloud-git-server
    container_name: my-cloud-git-server
    volumes:
      - /var/mycloud/volume/git/repos:/usr/local/apache2/htdocs/git
    ports:
      - '8090:80'
  my-cloud-mongodb:
    image: mongo
    container_name: my-cloud-mongodb
    environment:
      - MONGO_INITDB_DATABASE=myidsrvdb
      - MONGO_INITDB_ROOT_USERNAME=myidsrvdbuser
      - MONGO_INITDB_ROOT_PASSWORD=myidsrvdbpwd@1234
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - /var/mycloud/volume/db/mongo:/data/db
    ports:
      - '27017:27017'
  my-cloud-influxdb:
    image: influxdb
    container_name: my-cloud-influxdb
    environment:
      - INFLUX_USERNAME=todd
      - INFLUX_PASSWORD=influxdb4ever
    volumes:
      - /var/mycloud/volume/db/influx:/var/lib/influxdb
    ports:
      - '8086:8086'
  elasticsearch:
    image: elasticsearch:7.7.1
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    tty: true
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  # kibana:
  #   image: kibana:7.7.1
  #   container_name: kibana
  #   ports:
  #     - "5601:5601"
  my-cloud-discovery:
    image: developerhelperhub/my-cloud-discovery
    container_name: my-cloud-discovery
    links:
      - elasticsearch
    environment:
      - ENV_MYC_DISCOVERY_USERNAME=discovery
      - ENV_MYC_DISCOVERY_PASSWORD=discoverypass
      - ENV_MYC_DISCOVERY_HOST=my-cloud-discovery
      - ENV_MYC_DISCOVERY_PORT=8761
      - ENV_MYC_FILEBEAT_ELASTICSEARCH_HOSTS=["elasticsearch:9200"]
      - ENV_MYC_FILEBEAT_LOGGING_LEVEL="info"
      - ENV_MYC_DISCOVERY_JWT_SIGN_KEY=123456
      - |
        JAVA_OPTS=
        -Dspring.profiles.active=staging
        -Djava.rmi.server.logCalls=true
        -Djava.rmi.server.hostname=localhost
        -Dcom.sun.management.jmxremote=true
        -Dcom.sun.management.jmxremote.local.only=false 
        -Dcom.sun.management.jmxremote.port=7001
        -Dcom.sun.management.jmxremote.rmi.port=7001
        -Dcom.sun.management.jmxremote.ssl=false 
        -Dcom.sun.management.jmxremote.authenticate=false
    ports:
      - '8761:8761'
      - '9001:9001'
  my-cloud-config-server:
    image: developerhelperhub/my-cloud-config-server
    container_name: my-cloud-config-server
    links:
      - elasticsearch
      - my-cloud-git-server
      - my-cloud-discovery
    environment:
      - ENV_MYC_DISCOVERY_USERNAME=discovery
      - ENV_MYC_DISCOVERY_PASSWORD=discoverypass
      - ENV_MYC_DISCOVERY_HOST=my-cloud-discovery
      - ENV_MYC_DISCOVERY_PORT=8761
      - ENV_MYC_FILEBEAT_ELASTICSEARCH_HOSTS=["elasticsearch:9200"]
      - ENV_MYC_FILEBEAT_LOGGING_LEVEL="info"
      - ENV_MYC_CONFIG_SERVER_GIT_URI=http://my-cloud-git-server/my-cloud-config-repo.git
#      - ENV_MYC_CONFIG_SERVER_GIT_USERNAME=-
#      - ENV_MYC_CONFIG_SERVER_GIT_PASSWORD=-
      - ENV_MYC_CONFIG_SERVER_USERNAME=configserver
      - ENV_MYC_CONFIG_SERVER_PASSWORD=OpskJh88229qqq
      - |
        JAVA_OPTS=
        -Dspring.profiles.active=staging
        -Djava.rmi.server.logCalls=true
        -Djava.rmi.server.hostname=localhost
        -Dcom.sun.management.jmxremote=true
        -Dcom.sun.management.jmxremote.local.only=false 
        -Dcom.sun.management.jmxremote.port=7001
        -Dcom.sun.management.jmxremote.rmi.port=7001
        -Dcom.sun.management.jmxremote.ssl=false 
        -Dcom.sun.management.jmxremote.authenticate=false
    ports:
      - '8089:8089'
      - '9006:9006'
  my-cloud-identity:
    image: developerhelperhub/my-cloud-identity
    container_name: my-cloud-identity
    links:
      - elasticsearch
      - my-cloud-discovery
      - my-cloud-config-server
      - my-cloud-mongodb
    environment:
      - ENV_MYC_DISCOVERY_USERNAME=discovery
      - ENV_MYC_DISCOVERY_PASSWORD=discoverypass
      - ENV_MYC_DISCOVERY_HOST=my-cloud-discovery
      - ENV_MYC_DISCOVERY_PORT=8761
      - ENV_MYC_FILEBEAT_ELASTICSEARCH_HOSTS=["elasticsearch:9200"]
      - ENV_MYC_FILEBEAT_LOGGING_LEVEL="info"
      - ENV_MYC_CONFIG_SERVER_URI_PATH=http://my-cloud-config-server:8089
      - ENV_MYC_CONFIG_SERVER_USERNAME=configserver
      - ENV_MYC_CONFIG_SERVER_PASSWORD=OpskJh88229qqq
      - |
        JAVA_OPTS=
        -Dspring.profiles.active=staging
        -Djava.rmi.server.logCalls=true
        -Djava.rmi.server.hostname=localhost
        -Dcom.sun.management.jmxremote=true
        -Dcom.sun.management.jmxremote.local.only=false
        -Dcom.sun.management.jmxremote.port=7002
        -Dcom.sun.management.jmxremote.rmi.port=7002
        -Dcom.sun.management.jmxremote.ssl=false 
        -Dcom.sun.management.jmxremote.authenticate=false
    ports:
      - '8081:8081'
      - '9002:9002'
  my-cloud-api-gateway:
    image: developerhelperhub/my-cloud-api-gateway
    container_name: my-cloud-api-gateway
    links:
      - elasticsearch
      - my-cloud-discovery
      - my-cloud-config-server
    environment:
      - ENV_MYC_DISCOVERY_USERNAME=discovery
      - ENV_MYC_DISCOVERY_PASSWORD=discoverypass
      - ENV_MYC_DISCOVERY_HOST=my-cloud-discovery
      - ENV_MYC_DISCOVERY_PORT=8761
      - ENV_MYC_FILEBEAT_ELASTICSEARCH_HOSTS=["elasticsearch:9200"]
      - ENV_MYC_FILEBEAT_LOGGING_LEVEL="info"
      - ENV_MYC_CONFIG_SERVER_URI_PATH=http://my-cloud-config-server:8089
      - ENV_MYC_CONFIG_SERVER_USERNAME=configserver
      - ENV_MYC_CONFIG_SERVER_PASSWORD=OpskJh88229qqq
      - |
        JAVA_OPTS=
        -Dspring.profiles.active=staging
        -Djava.rmi.server.logCalls=true
        -Djava.rmi.server.hostname=localhost
        -Dcom.sun.management.jmxremote=true
        -Dcom.sun.management.jmxremote.local.only=false
        -Dcom.sun.management.jmxremote.port=7003
        -Dcom.sun.management.jmxremote.rmi.port=7003
        -Dcom.sun.management.jmxremote.ssl=false 
        -Dcom.sun.management.jmxremote.authenticate=false
    ports:
      - '8085:8085'
      - '9003:9003'
  my-cloud-monitor:
    image: developerhelperhub/my-cloud-monitor
    container_name: my-cloud-monitor
    links:
      - my-cloud-mongodb
      - my-cloud-influxdb
      - my-cloud-discovery
      - my-cloud-identity
      - elasticsearch
      - my-cloud-config-server
    environment:
      - ENV_MYC_DISCOVERY_USERNAME=discovery
      - ENV_MYC_DISCOVERY_PASSWORD=discoverypass
      - ENV_MYC_DISCOVERY_HOST=my-cloud-discovery
      - ENV_MYC_DISCOVERY_PORT=8761
      - ENV_MYC_FILEBEAT_ELASTICSEARCH_HOSTS=["elasticsearch:9200"]
      - ENV_MYC_FILEBEAT_LOGGING_LEVEL="info"
      - ENV_MYC_CONFIG_SERVER_URI_PATH=http://my-cloud-config-server:8089
      - ENV_MYC_CONFIG_SERVER_USERNAME=configserver
      - ENV_MYC_CONFIG_SERVER_PASSWORD=OpskJh88229qqq
      - |
        JAVA_OPTS=
        -Dspring.profiles.active=staging
        -Djava.rmi.server.logCalls=true
        -Djava.rmi.server.hostname=localhost
        -Dcom.sun.management.jmxremote=true
        -Dcom.sun.management.jmxremote.local.only=false
        -Dcom.sun.management.jmxremote.port=7004
        -Dcom.sun.management.jmxremote.rmi.port=7004
        -Dcom.sun.management.jmxremote.ssl=false 
        -Dcom.sun.management.jmxremote.authenticate=false
    ports:
      - '8087:8087'
      - '9004:9004'
  my-cloud-monitor-scheduler:
    image: developerhelperhub/my-cloud-monitor-scheduler
    container_name: my-cloud-monitor-scheduler
    links:
      - my-cloud-mongodb
      - my-cloud-influxdb
      - my-cloud-discovery
      - my-cloud-identity
      - my-cloud-config-server
    environment:
      - ENV_MYC_DISCOVERY_USERNAME=discovery
      - ENV_MYC_DISCOVERY_PASSWORD=discoverypass
      - ENV_MYC_DISCOVERY_HOST=my-cloud-discovery
      - ENV_MYC_DISCOVERY_PORT=8761
      - ENV_MYC_FILEBEAT_ELASTICSEARCH_HOSTS=["elasticsearch:9200"]
      - ENV_MYC_FILEBEAT_LOGGING_LEVEL="info"
      - ENV_MYC_CONFIG_SERVER_URI_PATH=http://my-cloud-config-server:8089
      - ENV_MYC_CONFIG_SERVER_USERNAME=configserver
      - ENV_MYC_CONFIG_SERVER_PASSWORD=OpskJh88229qqq
      - |
        JAVA_OPTS=
        -Dspring.profiles.active=staging
        -Djava.rmi.server.logCalls=true
        -Djava.rmi.server.hostname=localhost
        -Dcom.sun.management.jmxremote=true
        -Dcom.sun.management.jmxremote.local.only=false
        -Dcom.sun.management.jmxremote.port=7005
        -Dcom.sun.management.jmxremote.rmi.port=7005
        -Dcom.sun.management.jmxremote.ssl=false 
        -Dcom.sun.management.jmxremote.authenticate=false
    ports:
      - '8088:8088'
      - '9005:9005'

volumes:
    elasticsearch_data:
