spring:
  application:
    name: inventory-service
            
logging:
  level:
    org:
      springframework: DEBUG
    com:
      developerhelperhub: DEBUG

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:discoverypass@localhost:8761/eureka/