
spring:
  application:
    name: my-cloud-discovery
  security:
    user:
      name: ${ENV_MYC_DISCOVERY_USERNAME}
      password: ${ENV_MYC_DISCOVERY_PASSWORD}

logging:
  level:
    org:
      springframework: DEBUG
    com:
      developerhelperhub: DEBUG
      netflix:
        eureka: OFF
        discovery: OFF

server:
  port: 8761
  

eureka:
  dashboard:
    enabled: false
  client:
    serviceUrl:
      defaultZone: http://${ENV_MYC_DISCOVERY_USERNAME}:${ENV_MYC_DISCOVERY_PASSWORD}@${ENV_MYC_DISCOVERY_HOST}:${ENV_MYC_DISCOVERY_PORT}/eureka/
    #register-with-eureka: false
    #fetch-registry: false
  

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        exclude: "*" 
    jmx:
      exposure:
        include: info, health, metrics 
         