spring:
  application:
    name: my-cloud-discovery
  jmx:
    enabled: true
  security:
    user:
      name: ${ENV_MYC_DISCOVERY_USERNAME}
      password: ${ENV_MYC_DISCOVERY_PASSWORD}

mycloud:
  identity:
    jwt.sign-key: ${ENV_MYC_DISCOVERY_JWT_SIGN_KEY}
    
server:
  port: 8761
  tomcat:
    accesslog:
      enabled: true
      directory: /var/mycloud/logs/access_logs
      prefix: access_log
      buffered: false
      suffix: .log
      pattern: "%t|%a|%h|%p|%m|%U|%q|%s|%D|%T|%F|%l|%S|%I|%v|%u"

eureka:
  dashboard:
    enabled: false
  client:
    serviceUrl:
      defaultZone: http://${ENV_MYC_DISCOVERY_USERNAME}:${ENV_MYC_DISCOVERY_PASSWORD}@${ENV_MYC_DISCOVERY_HOST}:${ENV_MYC_DISCOVERY_PORT}/eureka/
    #register-with-eureka: false
    #fetch-registry: false
  instance:
    preferIpAddress: true

management:
  server:
    port: 9001
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - jolokia
    jmx:
      exposure:
        include:
          - info
          - health
          - metrics      