version: '3'
services: 
  my-cloud-mongodb:
    image: mongo
    container_name: my-cloud-mongodb
    # networks:
    #   mycloud_network:
    #     ipv4_address: 172.16.1.5
    environment:
      - MONGO_INITDB_DATABASE=myidsrvdb
      - MONGO_INITDB_ROOT_USERNAME=myidsrvdbuser
      - MONGO_INITDB_ROOT_PASSWORD=myidsrvdbpwd@1234
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - /tmp/db/my-cloud/mongo-volume:/data/db
    ports:
      - '27017:27017'
  my-cloud-influxdb:
    image: influxdb
    # networks:
    #   mycloud_network:
    #     ipv4_address: 172.16.1.2
    container_name: my-cloud-influxdb
    environment:
      - INFLUX_USERNAME=todd
      - INFLUX_PASSWORD=influxdb4ever
    volumes:
      - /tmp/db/my-cloud/influx-volume:/var/lib/influxdb
    ports:
      - '8086:8086'

networks:
  mycloud_network:
    external: true